import type { ProductType } from '@types';

export const topProducts: ProductType[] = [
    {
        title: 'Restaurant Booking App',
        slug: 'restaurant-booking-app',
        techStack: 'React and Bootstrap',
        sales: 70,
    },
    {
        title: 'Online Learning Platform',
        slug: 'online-learning-platform',
        techStack: 'Next.js and Tailwind CSS',
        sales: 120,
    },
    {
        title: 'Crypto Wallet Tracker',
        slug: 'crypto-wallet-tracker',
        techStack: 'Vue and Firebase',
        sales: 90,
    },
    {
        title: 'Fitness Goal Tracker',
        slug: 'fitness-goal-tracker',
        techStack: 'React Native and Redux',
        sales: 85,
    },
    {
        title: 'E-commerce Admin Panel',
        slug: 'ecommerce-admin-panel',
        techStack: 'Angular and NgRx',
        sales: 110,
    },
    {
        title: 'Job Listing Portal',
        slug: 'job-listing-portal',
        techStack: 'Django and PostgreSQL',
        sales: 75,
    },
    {
        title: 'AI Image Generator',
        slug: 'ai-image-generator',
        techStack: 'Next.js and OpenAI API',
        sales: 130,
    },
    {
        title: 'Note Taking App',
        slug: 'note-taking-app',
        techStack: 'React and MongoDB',
        sales: 92,
    },
    {
        title: 'Travel Planner',
        slug: 'travel-planner',
        techStack: 'Flutter and Firebase',
        sales: 80,
    },
    {
        title: 'Stock Market Tracker',
        slug: 'stock-market-tracker',
        techStack: 'React and Node.js',
        sales: 77,
    },
    {
        title: 'Real Estate Dashboard',
        slug: 'real-estate-dashboard',
        techStack: 'Vue and Tailwind CSS',
        sales: 88,
    },
    {
        title: 'Event Management App',
        slug: 'event-management-app',
        techStack: 'React and Express.js',
        sales: 73,
    },
    {
        title: 'Book Sharing Platform',
        slug: 'book-sharing-platform',
        techStack: 'Laravel and Vue',
        sales: 62,
    },
    {
        title: 'Budget Planner',
        slug: 'budget-planner',
        techStack: 'React and Chart.js',
        sales: 65,
    },
    {
        title: 'Food Delivery App',
        slug: 'food-delivery-app',
        techStack: 'React Native and Firebase',
        sales: 150,
    },
    {
        title: 'Online Survey Tool',
        slug: 'online-survey-tool',
        techStack: 'Angular and Node.js',
        sales: 78,
    },
    {
        title: 'E-learning Quiz App',
        slug: 'e-learning-quiz-app',
        techStack: 'Vue and Supabase',
        sales: 55,
    },
    {
        title: 'Startup Portfolio Website',
        slug: 'startup-portfolio-website',
        techStack: 'Next.js and Sass',
        sales: 97,
    },
    {
        title: 'AI Chatbot App',
        slug: 'ai-chatbot-app',
        techStack: 'React and OpenAI API',
        sales: 115,
    },
    {
        title: 'Pet Adoption Platform',
        slug: 'pet-adoption-platform',
        techStack: 'Django and React',
        sales: 61,
    },
    {
        title: 'Expense Splitter',
        slug: 'expense-splitter',
        techStack: 'Vue and Firebase',
        sales: 68,
    },
    {
        title: 'News Aggregator',
        slug: 'news-aggregator',
        techStack: 'Next.js and News API',
        sales: 102,
    },
    {
        title: 'To-do List App',
        slug: 'todo-list-app',
        techStack: 'React and TypeScript',
        sales: 79,
    },
    {
        title: 'Language Learning App',
        slug: 'language-learning-app',
        techStack: 'Flutter and Supabase',
        sales: 86,
    },
    {
        title: 'Freelancer Hiring Platform',
        slug: 'freelancer-hiring-platform',
        techStack: 'Node.js and MongoDB',
        sales: 84,
    },
    {
        title: 'Crypto Price Ticker',
        slug: 'crypto-price-ticker',
        techStack: 'React and CoinGecko API',
        sales: 58,
    },
    {
        title: 'Resume Builder',
        slug: 'resume-builder',
        techStack: 'Vue and Express',
        sales: 83,
    },
    {
        title: 'Music Streaming App',
        slug: 'music-streaming-app',
        techStack: 'React and Spotify API',
        sales: 118,
    },
    {
        title: 'Weather Dashboard',
        slug: 'weather-dashboard',
        techStack: 'Vue and OpenWeatherMap API',
        sales: 69,
    },
    {
        title: 'Donation Platform',
        slug: 'donation-platform',
        techStack: 'Laravel and MySQL',
        sales: 66,
    },
    {
        title: 'Remote Job Board',
        slug: 'remote-job-board',
        techStack: 'Next.js and PostgreSQL',
        sales: 99,
    },
    {
        title: 'Parking Finder',
        slug: 'parking-finder',
        techStack: 'React Native and Mapbox',
        sales: 59,
    },
    {
        title: 'Quiz Builder',
        slug: 'quiz-builder',
        techStack: 'Vue and Supabase',
        sales: 60,
    },
    {
        title: 'Online Portfolio Generator',
        slug: 'online-portfolio-generator',
        techStack: 'React and Framer Motion',
        sales: 74,
    },
    {
        title: 'Fashion Storefront',
        slug: 'fashion-storefront',
        techStack: 'Next.js and Stripe',
        sales: 123,
    },
    {
        title: 'Car Rental App',
        slug: 'car-rental-app',
        techStack: 'React and Redux',
        sales: 91,
    },
    {
        title: 'Virtual Whiteboard',
        slug: 'virtual-whiteboard',
        techStack: 'Canvas API and React',
        sales: 67,
    },
    {
        title: 'Event Ticketing App',
        slug: 'event-ticketing-app',
        techStack: 'Angular and Firebase',
        sales: 87,
    },
    {
        title: 'AI Resume Analyser',
        slug: 'ai-resume-analyser',
        techStack: 'Python and Streamlit',
        sales: 45,
    },
    {
        title: 'Remote Interview Tool',
        slug: 'remote-interview-tool',
        techStack: 'React and WebRTC',
        sales: 76,
    },
    {
        title: 'Invoice Generator',
        slug: 'invoice-generator',
        techStack: 'Vue and PDFKit',
        sales: 64,
    },
    {
        title: 'HR Management System',
        slug: 'hr-management-system',
        techStack: 'Django and React',
        sales: 81,
    },
    {
        title: 'File Sharing Platform',
        slug: 'file-sharing-platform',
        techStack: 'Node.js and WebSocket',
        sales: 72,
    },
    {
        title: 'Blog CMS',
        slug: 'blog-cms',
        techStack: 'Next.js and Sanity',
        sales: 94,
    },
    {
        title: 'College ERP System',
        slug: 'college-erp-system',
        techStack: 'Laravel and Vue.js',
        sales: 79,
    },
    {
        title: 'Virtual Internship Portal',
        slug: 'virtual-internship-portal',
        techStack: 'React and Supabase',
        sales: 66,
    },
    {
        title: 'Online Exam App',
        slug: 'online-exam-app',
        techStack: 'Vue and Firebase',
        sales: 82,
    },
    {
        title: 'Recipe Sharing Platform',
        slug: 'recipe-sharing-platform',
        techStack: 'React and GraphQL',
        sales: 90,
    },
    {
        title: 'Digital Clock App',
        slug: 'digital-clock-app',
        techStack: 'React and Styled Components',
        sales: 55,
    },
    {
        title: 'AI Presentation Builder',
        slug: 'ai-presentation-builder',
        techStack: 'Next.js and GPT-4',
        sales: 113,
    },
    {
        title: 'Social Media Dashboard',
        slug: 'social-media-dashboard',
        techStack: 'Vue and Tailwind CSS',
        sales: 88,
    },
    {
        title: 'E-book Reader App',
        slug: 'ebook-reader-app',
        techStack: 'Flutter and Firebase',
        sales: 93,
    },
    {
        title: 'Voice Notes App',
        slug: 'voice-notes-app',
        techStack: 'React Native and Expo',
        sales: 70,
    },
    {
        title: 'Marketplace for Creators',
        slug: 'marketplace-for-creators',
        techStack: 'Next.js and MongoDB',
        sales: 101,
    },
];
